best_trial: 10
best_trial_save_dir: best/
config_paths:
- config/3sources.yaml
dataset_args:
  mat_path: data/3sources.mat
  topk: 15
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/3sources.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/3sources
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights: null
metric_acc:
  mean: 1.0
  std: 0.0
metric_f1:
  mean: 1.0
  std: 0.0
metric_precision:
  mean: 1.0
  std: 0.0
metric_recall:
  mean: 1.0
  std: 0.0
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 88
  lamda: 0.43203504141501803
  layerclass: GCNIILayer
  nlayer: 2
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/3sources
tsd_nt: temp_result/
tt_nt: 1
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 250
val_metric_acc:
  mean: 0.8137254939999998
  std: 0.013787587171029013
val_metric_f1:
  mean: 0.6645254682008255
  std: 0.017934961783621764
val_metric_precision:
  mean: 0.6897306038120906
  std: 0.022834356184465245
val_metric_recall:
  mean: 0.7255047668962763
  std: 0.02522746621232546
weight_decay1: 0.01
weight_decay2: 0.0005
