best_trial: 10
best_trial_save_dir: best/
config_paths:
- config/NGs.yaml
dataset_args:
  mat_path: data/NGs.mat
  topk: 31
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/NGs.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/NGs
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights: null
metric_acc:
  mean: 1.0
  std: 0.0
metric_f1:
  mean: 1.0
  std: 0.0
metric_precision:
  mean: 1.0
  std: 0.0
metric_recall:
  mean: 1.0
  std: 0.0
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 72
  lamda: 0.6939582335992862
  layerclass: GCNIILayer
  nlayer: 2
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/NGs
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 5
val_metric_acc:
  mean: 0.953777784
  std: 0.00870929733952767
val_metric_f1:
  mean: 0.9540696243060856
  std: 0.008632552879820423
val_metric_precision:
  mean: 0.9584641639388123
  std: 0.0073773208510499785
val_metric_recall:
  mean: 0.9537104706073929
  std: 0.008787801919894067
weight_decay1: 0.01
weight_decay2: 0.0005
