best_trial: 1
best_trial_save_dir: temp_result/
config_paths:
- best/NGs/conf.yaml
dataset_args:
  mat_path: data/NGs.mat
  topk: 31
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/conf.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/conf
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
loss_weights: null
metric_acc:
  mean: 1.0
  std: 0.0
metric_f1:
  mean: 1.0
  std: 0.0
metric_precision:
  mean: 1.0
  std: 0.0
metric_recall:
  mean: 1.0
  std: 0.0
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 72
  lamda: 0.6939582335992862
  layerclass: GCNIILayer
  nlayer: 2
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: false
result_dir: temp_result/
run_times: 1
scheduler_args:
  factor: 0.3
  min_lr: 1.0e-08
  mode: min
  patience: 10
  verbose: false
scheduler_class_args:
  class_name: ReduceLROnPlateau
  module_path: torch.optim.lr_scheduler
scheduler_monitor: val_loss
tbwriter_args:
  log_dir: ./logs/conf
tsd_nt: temp_result/
tt_nt: 1
tuner_flag: false
tuner_monitor: val_metric_acc
tuner_n_repeats: 5
tuner_n_trials: 250
val_metric_acc:
  mean: 0.94666666
  std: 0.0
val_metric_f1:
  mean: 0.9477204029471712
  std: 0.0
val_metric_precision:
  mean: 0.9525818652690626
  std: 0.0
val_metric_recall:
  mean: 0.9469500081419964
  std: 0.0
weight_decay1: 0.01
weight_decay2: 0.0005
